### ISSUE TITLE
License should be inherited as well.

### ISSUE THREAD

**Issue by Fleshgrinder** [phpDocumentor/fig-standards#100]
Currenlty `@version`, `@author`, and `@copyright` are always inherited. However, `@license` should be added to that list in my opinion.

See [6. Inheritance](https://github.com/phpDocumentor/fig-standards/blob/master/proposed/phpdoc.md#6-inheritance).

**Comment by ashnazg** [comment]
I think that `@license` was never made hereditary because of the possibility of my more strictly licensed class extending from a more loosely licensed class, and thus the potential for incorrect licensing to appear in documentation.  That could be more of a Oh Crap issue than other unintentional tags appearing.

Ping @ondrejmirtes @muglug @neuro159 @mindplay-dk @GaryJones @mvriel @jaapio for opinions.

**Comment by mvriel** [comment]
I think that hereditary meta-tags are interesting as is and can induce unwanted side effects (such as the `@author` appearing in a file for which someone is not the author). If anything, I would prefer less hereditary tags :)

**Comment by ashnazg** [comment]
Looks like a no-go.
