### ISSUE TITLE
FQSEN, we need to make the "fully" optional.

### ISSUE THREAD

**Issue by Fleshgrinder** [phpDocumentor/fig-standards#106]
Emphasize mine:

> Note that for namespaced names (fully qualified namespace names containing namespace separator, such as Foo\Bar as opposed to global names that do not, such as FooBar), **the leading backslash is** unnecessary and **not recommended**, as import names must be fully qualified, and are not processed relative to the current namespace.
>
> — [PHP Manual: Using namespaces: Aliasing/Importing](https://secure.php.net/language.namespaces.importing)

We are currently requiring the backslash at the beginning for every tag that accepts an FQSEN. I fiddle around with PHPUnit yesterday and it sometimes accepts FQSENs without the leading backslash, but for instance does not with the `@expectedException` tag.

This is weird and limiting all tags to accept only FQSENs with a leading backslash could or would solve this issue (as it is now). However, the manual clearly states that it is not recommended. Additionally, we clearly remove any ability for class names referencing class aliases from the use statement in classes. Consider the following:

```php
use My\Namespace\MyClass as YourClass;

interface AnotherClass
{
    /**
     * @param YourClass $yourClass
     */
    public function doSomething(YourClass $yourClass);
}
```

This is currently not possible, because `YourClass` is not a valid FQSEN. (See [Appendix A: Type ABNF](https://github.com/phpDocumentor/fig-standards/blob/master/proposed/phpdoc.md#abnf).)

IDEs like PhpStorm support this via the annotation plugin. PHPUnit also has support for shortened FQSENs that reference other tags (e.g. `@coversDefaultClass` paired with `@covers`); but it currently does not support even shorter references that reference aliases from the use section. Even though, that would highly reduce the amount of characters that one has to type. Consider the following example:

```php
namespace PhpDocumentor\Component\Value;

use PhpDocumentor\Component\Reflection\ReflectionClass;
use PHPUnit_Framework_TestCase;

/**
 * Resolve to current namespace:
 *
 * @coversDefaultClass DocComment
 * @usesDefaultClass DocComment
 */
class DocCommentTest extends PHPUnit_Framework_TestCase
{
    /**
     * @covers ::method1
     * @uses ::method2
     * @uses PhpDoc<extended> Same namespace!
     * @uses ReflectionClass<extended> From use statement above.
     */
    public function testSomething()
    {
        $this->assertTrue(true);
    }
}
```

Note, I choose a PHPUnit example because it makes use of a lot of these relations, but the actual issue is regarding any and all tags that currently require an FQSEN.

**Comment by mvriel** [comment]
I think you mistake a FULLY Qualified Structural Element Name with a Qualified Structural Element Name. Please read this manual entry for the difference between a Qualified, Unqualified and Fully Qualified Name: http://php.net/manual/en/language.namespaces.rules.php.

So in short:

Fully Qualified Structural Element Name
    This is a complete Element Name including preceding slash and is comparable to an absolute path

Qualified Structural Element Name
    This is an Element name that is not preceded by a slash and is generally comparable to a relative path. Based on the Namespace Resolution rules of PHP this can be resolved to a FQSEN

Unqualified Structural Element Name
    The last part of a complete Namespaced name that is generally not resolveable to a QSEN of FQSEN.

**Comment by Fleshgrinder** [comment]
I understand the differences, it's just that some elements are restricted to use only FQSEN, namely:

- [`@see`](https://github.com/phpDocumentor/fig-standards/blob/master/proposed/phpdoc.md#816-see)
- [`@uses`](https://github.com/phpDocumentor/fig-standards/blob/master/proposed/phpdoc.md#823-uses)

I just realized that the backslash at the beginning is indeed optional for the type, so that's a good thing. I think that every tag should be able to consume all kinds (FQSEN, QSEN, and USEN) as well as any aliases from the use section at the top. This should not be hard to accomplish, because one can utilize PHP's auto-loading to resolve all of them.

**Comment by mvriel** [comment]
Tags can't use a USEN; you can't resolve a USEN to a QSEN or FQSEN and is meaningless as Element identifier

**Comment by mvriel** [comment]
And your assumption that this is not hard to do is not true; that only works if a parser has access to all referred Elements and this is not the case. Also: using Dynamic Reflection makes for poor performance so, for example, phpDocumentor uses Static Reflection. Which means that you need to do all that resolving yourself

**Comment by mvriel** [comment]
You do however have a point that the current definition of the `@uses` and `@see` do not permit a QSEN; phpDocumentor for example does support the use of QSENs in that location so I guess we should allow the use of a QSEN in the tag signature

**Comment by Fleshgrinder** [comment]
I have never written a software like phpDocumentor, I am merely stating what I would like from the view of a documenter. Simply because always writing FQSENs and QSENs results in a lot of clutter.

I cannot refer to an element as documenter that I do not have access to, of course I am forced to use an FQSEN or QSEN then.

However, I should be able to refer to classes that are:

- in the same namespace without anything,
- aliased in the use segment.

I think that this is solvable with offline reflection, by simply creating a class map. You will have to parse all files anyways. I guess this would need a prototype.

**Comment by ezzatron** [comment]
@Fleshgrinder unfortunately @mvriel is correct in that it is no simple task to resolve symbols against `use` statements. I have intimate experience with the complexity, because I wrote a library for exactly that purpose (see [this branch](https://github.com/eloquent/cosmos/tree/feature/pathogen-based) of my library 'Cosmos' for the most up-to-date implementation).

*However*, if I'm reading this ticket correctly, we're all agreeing that `@see` and `@uses` should allow the use of shorter class names, because writing out the full class name every time is tedious.

This would be consistent with the treatment of class names in `@param` and `@return` tag types. From [Valid Class Name](https://github.com/phpDocumentor/fig-standards/blob/master/proposed/phpdoc.md#valid-class-name):

> A valid class name seen from the context where this type is mentioned. Thus this may be either a Fully Qualified Class Name (FQCN) or if present in a namespace a local name.

I think the ideal would be to treat class names, in every context, *exactly* as the PHP interpreter does (which is what Cosmos aims to do). I believe that would be the most intuitive method for most developers, and well worth the complexity it adds.

I'm happy to lend my time to helping out with implementations. For instance, I have an [open PR on PHPUnit](https://github.com/sebastianbergmann/phpunit/pull/1312) for adding similar support there.

**Comment by Fleshgrinder** [comment]
No alias support is fine, as long as one does not have to write out the full class name all the time, as is the case in PHPUnit and it is awesome that you are already helping there to get this sorted out as well. :+1:

**Comment by mvriel** [comment]
All tags that refer to elements should support Valid Class Names (as used above) and hence support aliasing using use statements. PhpDocumentor's own TypeResolver library supports this as well.

I will take this note into account when proof reading the document before the review phase so that the wording reflects this.
