### ISSUE TITLE
Namespace automatically defines @package - suggestion

### ISSUE THREAD

**Issue by jacobsantos** [phpDocumentor/fig-standards#108]
I'm not sure if this should be part of the specification, but I have always thought that phpDocumentor used as many available PHP constructs as possible when making tags optional.

**Suggestion** PHP namespace defines default `@package` provided `@package` is missing. It would replace the need for defining `@package` in files. Having `@package` in a file would override any namespace to allow for overriding and for projects that already have `@package` definitions.

**Comment by mindplay-dk** [comment]
As far as my understanding, we only got `@package` in the first place as a means of "emulating" namespaces before PHP had that.

However, the definition in the current spec says:

> Namespaces provide a functional subdivision of "Structural Elements" where the @package tag can provide a logical subdivision in which way the elements can be grouped with a different hierarchy.

So it's a different hierarchy from namespaces.

Though I can't claim I understand why we need two hierarchies to begin with. I think only legacy code (e.g. pre-namespaces PEAR packages) even use this tag?

Also, this:

> Each level in the logical hierarchy MUST separated with a backslash (\) to be familiar to Namespaces

Yikes. So they're *not* namespaces, but let's make them resemble namespace as much as possible, because, what, just to maximize the confusion?

If I could have my way, we would just drop this feature entirely. It is primarily a relic from a time before namespaces, and I don't know why anyone would need it by now.

**Comment by GrahamCampbell** [comment]
Yeh. I think the package tag should actually be removed.

**Comment by jacobsantos** [comment]
Namespaces are an optional feature. Also you may want to override the php namespace.

Does this mean that implementations should already use namespaces to group functions and objects per the current spec? I did not use phpdocumentor with namespaces, nor any other phpdoc application. Do they really do this?

It seems like there is a bit of confusion then because I do see projects that even without the file level docblock still define a `@package` matching the namespace. Perhaps the spec could be updated to clarify that this is already the define or proposed behavior.

**Comment by jacobsantos** [comment]
@mindplay-dk many projects use the `@package` tag. Probably outside the FIG group, I haven't looked at all of the FIG member projects. WordPress is a popular one at least and is unlikely to move to namespaces in the near future.

**Comment by GrahamCampbell** [comment]
Just because some projects choose to use that annotation, it doesn't mean we have to include it in the spec. Such projects aren't supported by psr0/psr4 for example.

**Comment by mvriel** [comment]
At this point I see no reason to remove the package tag from the specification nor to provide a default in case it is omitted (because no package is specified in that case). The wording may be subject to be revised but proof reading will discern such a need.

At current there is a significant number of projects that still use this tag and unless more than the majority of the member projects indicate a desire to drop this tag during the review phase or in a poll this will remain how it is.

**Comment by mindplay-dk** [comment]
> I do see projects that even without the file level docblock still define a `@package` matching the namespace

PhpStorm auto-generates that - people at work leave it there, I don't think they care or know what it's for. They definitely don't use it, nor do they need it for anything.

> At this point I see no reason to remove the package tag from the specification nor to provide a default

I agree, sort of reluctantly. There's no real reason to remove it, other than it's pointless. It doesn't add any information of any use to anyone, people or machines. We have namespaces, and we have Composer package names, and those actually mean something - the package tag is informational, at best, though I don't understand what information it conveys anymore.

As such, I agree though, it isn't doing any harm, it's just one of those junk annotations like `@author` or `@copyright`, just noise you learn to filter out automatically - there's no pressing reason to remove it.
