### ISSUE TITLE
Support to @as annotation

### ISSUE THREAD

**Issue by rentalhost** [phpDocumentor/fig-standards#111]
**Original:** https://youtrack.jetbrains.com/issue/WI-28737

It should allow you specify that a class, method or function works exactly on same way that another one. It's very common when you create a helper or a shortcut to another method. For instance:

```
<?php

class Math 
{
    /**
     * Sum two terms and returns it results.
     *
     * @param integer $a Left term.
     * @param integer $b Right term.
     * 
     * @return integer Sum of left and right terms.
     */
    public static function sum($a, $b) 
    {
        return $a + $b;
    }
}

/**
 * @as Math::sum
 */
function sum($a, $b) 
{
    return call_user_func_array("Math::sum", func_get_args());
}
```

Then, `sum()` will show informations exactly as `Math::sum()`.

But, it not can be limited to only a direct reference. It should allow you create a signature based on destiny method signature. For instance:

```
<?php

/**
 * Do something.
 *
 * @param int $left Left param.
 * @param int $right Right param.
 * @param string $operator Operator.
 * @param int $delta Delta.
 */
Something::with($left, $right, $operator, $delta);

/**
 * Note that I not define `$operator`, because the function will fill it for me.
 * @param float $delta It'll overwrite parent `$delta`.
 * @as Something::with
 */
Something::withSum($left, $right, $delta) {
    return Something::with($left, $right, '+', (int) ( $delta * 0.1 ));
}

```

It'll be useful both to generate docs or to help IDE. On doc, it can help to display the object information based on another object. To IDE will help with informations and object types.

For second example, it should create a doc like:

> Do something.
> Note that I not define `$operator`, because the function will fill it for me.
> **Attributes**: `$left`, `$right`, `$delta` (_with specifications_).
> **As in**: `Something::with` (_click to show_)

**Other possibles annotation signatures:** `@like`, `@asin`, `@same`, `@parent`, `@uses`...

**Comment by Fleshgrinder** [comment]
The `@uses` tag is already in widespread use in PHPUnit and we should not use it for anything else.

I like the basic idea and the fact that it actually has use cases. However, your first use case would be more precisely covered with an `@alias <FQSEN>` tag as this would be most descriptive. Additionally I think that an extension of the `@inheritDoc` tag to `@inheritDoc [FQSEN]` should do the trick for your second example and the same inheritance rules that apply to that tag should apply here.

We should not introduce ambiguous tags that try to cover more than one use case, this will yield too much confusion in the future.

**Comment by ashnazg** [comment]
I've seen this use case before with `@alias`, but I'm still -1 on the idea.

Ping @ondrejmirtes @muglug @neuro159 @mindplay-dk @GaryJones @mvriel @jaapio for opinions.

**Comment by jaapio** [comment]
I don't understand the use of this tag. And I do not understand why anyone would write code like in the example. If you want to reference a element to another element you can use `@see` no need for a special inheritdoc see like tag.

**Comment by mvriel** [comment]
I am very interested to see if there is a greater need for this. At the moment I am not convinced that this will pan out as you'd expect. 

For me, the problem lies in that the method references another method's description but there is no contract or guarantee that a refactoring won't change the way the host method's signature looks. At this point, the consuming method won't be covered anymore.

My personal preference is to duplicate the description in these type of instances (as you would duplicate test cases in similar unit tests) so that the documentation stays near each method and a change in either won't break

**Comment by rob006** [comment]
The most basic use case is trait which provide an implementation of interface. To document trait itself you need to copy-paste phpdoc from the interface and always keep it in sync. Or use `@see` which is not really convenient (why I need to go somewhere else to see documentation of this method?).

There are also cases where some methods are simple wrappers and/or provides syntactic sugar for existing methods, for example [`where()`](https://www.yiiframework.com/doc/api/2.0/yii-db-queryinterface#where()-detail) and [`andWhere()`](https://www.yiiframework.com/doc/api/2.0/yii-db-query#andWhere()-detail) from Yii Framework. Both shares the same syntax for `$condition`, which is pretty well explained in `where()` phpdoc, but not in `andWhere()` (and similar methods) because it will require copy-paste the same documentation in multiple places. As a framework consumer it is pretty annoyed that I need to go to different method documentation to see how can I use `andWhere()`.

**Comment by mindplay-dk** [comment]
To me, what's really interesting about this feature is the ability for tools to type-check: if you say your function is "like" another function, it should also have an identical argument types/order and return-type.

At this time, however, I have strong reservations about expanding the scope of the PSR, which is already years and years in the making.

**Comment by neuro159** [comment]
+1 for all the reservations.

@see is enough. And add some local description WHY you have it this way.

**Comment by ashnazg** [comment]
Looks like a no-go.
