### ISSUE TITLE
PSR-5 Variadic parameters

### ISSUE THREAD

**Issue by rbairwell** [phpDocumentor/fig-standards#121]
Could it be made clear in PSR-5 (PHPDocs) what the proposed standard for variadic parameters documentation should be. There currently appears to be numerous conflicting "standards" in existence:

``` php
<?php

/**
 * Docblock suggested by PHPStorm.
 *
 * @param DateInterval[] ...$intervals Test.
 */
function a(DateInterval ...$intervals)
{

}//end a()

/**
 * Docblock from http://stackoverflow.com/a/22271044/136771 .
 * (Doxygen)
 *
 * @param DateInterval $intervals,... Test.
 */
function b(DateInterval ...$intervals)
{

}//end b()

/**
 * A different one I've seen..
 *
 * @param DateInterval ... $intervals Test.
 */
function c(DateInterval ...$intervals)
{

}//end c()

/**
 * Docblock from http://stackoverflow.com/a/14513563/136771 .
 * (phpDocumentor)
 * 
 * @param DateInterval $internals,... Test.
 */
function d(DateInterval ...$intervals)
{

}//end d()


/**
 * Docblock from
 * https://github.com/phpDocumentor/phpDocumentor2/issues/629
 * and
 * https://philsturgeon.uk/php/2013/08/30/potential-variadic-function-syntax-for-php-56/
 *
 * @param DateInterval ...$internals Test.
 */
function e(DateInterval ...$intervals)
{

}//end e()
```

[cross-referenced to PHP Code Sniffer issue - https://github.com/squizlabs/PHP_CodeSniffer/issues/841 ]

**Comment by Fleshgrinder** [comment]
The current consensus here is the last example you posted, in other words, exactly as PHP has it in its signature. See #40, #86 and #87. However, note that the current pull request is not up-to-date to the actual discussion.

**Comment by Hast** [comment]
Any news about this one?

**Comment by Fleshgrinder** [comment]
PSR-5 is on hold completely, and it does not seam as if it would come back any time soon.

**Comment by Hast** [comment]
@Fleshgrinder what's the reason? Is there any problem with processing this PSR? Sorry, I'm just not quite aware of the situation.

**Comment by Fleshgrinder** [comment]
https://groups.google.com/forum/#!searchin/php-fig/mike$20van$20riel|sort:date/php-fig/KH7UF7qAuUo/FEr4PvZnAQAJ

**Comment by ashnazg** [comment]
Variadics are not mentioned in the current drafts, but probably do need to be.

**Comment by neuro159** [comment]
PhpStorm supports only `@param DateInterval[] ...$intervals Test.` since 2014 -
BEFORE variadics were approved into PHP syntax and ppl used stuff like `@param mixed $_ [optional] ` + `func_get_args()` in code.
Original user case for the feature is in the request  https://youtrack.jetbrains.com/issue/WI-20157
I just copied RFC language variadics syntax for consistency as did https://github.com/phpDocumentor/phpDocumentor2/issues/629.

Will generate the same format.
But built-in static analyser will *not* complain when `...` @in param is missing.

After having variadics in actual language for so long its use is not too important, but will be nice to have fix one valid format.

**Comment by ashnazg** [comment]
Ok, so the accepted syntax is `@param ...$second`... and we just need to get it into the PSR docs.  Maybe an explanation section in `phpdoc.md`... maybe requires something to change in the ABNF too... and perhaps show it in example tags in `phpdoc-tags.md`.

**Comment by TysonAndre** [comment]
> PhpStorm supports only `@param DateInterval[] ...$intervals Test.`

Psalm and Phan both expect `@param DateInterval ...$internals` for code such as `function c(DateInterval ...$intervals) { }` (can also be used in the absense of real types)

- Having `DateInterval ...` instead of `DateInterval[] ...` matches the syntax of real signatures
- I think that Psalm supported `@param DateInterval[] $intervals` and `@param array<int,DateInterval>` (when the `...` was absent) - I'm not 100% sure of that. See https://github.com/vimeo/psalm/blob/2.0.12/tests/VariadicTest.php#L21-L26

https://github.com/vimeo/psalm/blob/2.0.12/tests/VariadicTest.php#L87-L92

---

Additionally, there's an open ticket for PHPStorm ("Wrong PHPdoc parameter type generated for variadics") at https://youtrack.jetbrains.com/issue/WI-29429#comment=27-2680697 linking to this GitHub issue that requests that PHPStorm change the syntax to `@param DateInterval ...$internals` for that example.

**Comment by ashnazg** [comment]
This is now on the ML -- https://groups.google.com/forum/#!topic/php-fig/zFMcfjYAS7M
