### ISSUE TITLE
Describing anonymous functions (typo in TOC)

### ISSUE THREAD

**Issue by jankramer** [phpDocumentor/fig-standards#19]
I was wondering if describing the arguments/return value of anonymous functions was taken into account of this proposal, when I saw 

```
8. Describing anonymous functions
8. Tags
```

The Section 8 that has been written describes tags, so I guess there was a plan to describe anonymous functions but the section still has to be written?

**Comment by texdc** [comment]
Beuler?

I like @mindplay-dk's [first suggestion](https://github.com/phpDocumentor/fig-standards/issues/19#issuecomment-30012688) as requiring an abstract class just for documentation purposes is unacceptable.

**Comment by mindplay-dk** [comment]
> requiring an abstract class just for documentation purposes is unacceptable

Agreed, that was a bad idea.

Now, quoting my past self:

> callable functions are actually types, and as such I don't like the idea of declaring them inline

For a moment, I disagreed with myself, but then came back around after really thinking this through - I don't see the point of being able to declare function signatures inline, in fact, I see it as problematic, for several reasons:

  1. This will complicate the type syntax, which
  2. Complicates implementation, and
  3. Doesn't refactor well (when you realize you need to document the arguments or return value of functions matching that signature, and have to switch to a typedef), and
  4. Encourages duplication (by tempting you to copy/paste signatures when adding new members of the same type, as opposed to refactoring to a typedef), and lastly
  5. Overlaps with typedef, which can already support this

The latter point is critical, since allowing `@param` and `@return` in typedefs will also permit the definition of e.g. classes that act as callables by implementing `__invoke()`.

Where are we on this? Has anything been written? Let's bring this to a close. Let me know if you want me to type something up.

**Comment by jcchavezs** [comment]
@jankramer @mindplay-dk what is the status on this one? Did we agree on how to implement signature for callables? (here or in other issue)

**Comment by BafS** [comment]
Any news about this issue ?

**Comment by ashnazg** [comment]
If this needs to be pursued further, please bring this up as a new thread on the FIG mailing list for discussion -- https://groups.google.com/forum/#!forum/php-fig
