### ISSUE TITLE
Multi-word @package

### ISSUE THREAD

**Issue by GaryJones** [phpDocumentor/fig-standards#27]
Can some explicit guidance be given on how same-level multi-word `@package` tags should be given? Space separated? Hyphen-separated? Underscore_separated? CamelCase?
- `@package My\Coca Cola\Plugin`
- `@package My\Coca-Cola\Plugin`
- `@package My\Coca_Cola\Plugin`
- `@package My\CocaCola\Plugin`

**Comment by ashnazg** [comment]
I would do this camelCased myself.  Spaces are pretty much out of the question... otherwise parsing rules go nuts.

I don't see any reason the spec should show any preference for which non-space connector character is used.

Ping @ondrejmirtes @muglug @neuro159 @mindplay-dk @GaryJones @mvriel @jaapio for opinions.

**Comment by jaapio** [comment]
Since a description is allowed for the `@package` tag I wouldn't try to accept any spaces in the package name. The name of the package MUST be an expression without `space` characters. All other characters are allowed. I think we should state that it should be a valid `FQNN` (Fully Qualified Namespace Name)

**Comment by ashnazg** [comment]
If this needs to be pursued further, please bring this up as a new thread on the FIG mailing list for discussion -- https://groups.google.com/forum/#!forum/php-fig
