### ISSUE TITLE
Yield?

### ISSUE THREAD

**Issue by mvriel** [phpDocumentor/fig-standards#5]
Do we need something for the yield keyword or does @return suffice?

**Comment by jacobsantos** [comment]
A generator is a form of iterator. If you are using it as a co-routine, then it becomes a special iterator, one that accepts values called on the iterator. The language construct makes the pattern easily to implement with fewer lines and adds convention. There is only one way for generators and co-routines to work.

**Comment by nikic** [comment]
To summarize, there are five primary types involved in a generator:

 * The type returned by caling the generator function, which is `Generator`.
 * The value type `V` returned by `Generator::current()` (value).
 * The key type `K` returned by `Generator::key()`
 * The send type `S` which `Generator::send()` accepts as the argument.
 * The return type `R`  which is returned by `Generator::getReturn()` which is likely to be added in PHP 7.

So essentially a generator function returns a `Generator<V, K, S, R>` type.

PHP 7 return type annotations for generators can use just `Generator` (or `Iterator` or `Traversable`) - more detailed information about the yielded values etc is not possible due to the lack of generics.

As such I think phpdoc should use `@return Generator` and support additional generic arguments if possible, though probably just having `V` and `K` is enough for most practical purposes.

**Comment by MarkBaker** [comment]
Is it necessary to have a further type for Exceptions thrown into a generator that the generator can catch?

**Comment by nikic** [comment]
@MarkBaker Theoretically yes, one could further specialize this. But it's probably good enough to just keep `throw()` accepting an `Exception` object without further specifying which exception objects exactly are "accepted". It's usually a different type for every potentially throwing yield anyway. (It depends more on the function that is being called by the yield.)

**Comment by mvriel** [comment]
For arrays and array-like constructs, such as collection objects, there should be a simple way to declare what key and value types they contain. I think generators can benefit from this as well.

Unless a more specific notation is necessary (and proposed, because I am lacking in detailed enough knowledge on coroutines) this is currently the best that I can come up with

**Comment by ashnazg** [comment]
If this needs to be pursued further, please bring this up as a new thread on the FIG mailing list for discussion -- https://groups.google.com/forum/#!forum/php-fig
