### ISSUE TITLE
Misleading example in PSR-5: 8.13

### ISSUE THREAD

**Issue by loren-osborn** [phpDocumentor/fig-standards#58]
I was very glad to learn of [PSR-5](https://github.com/phpDocumentor/fig-standards/blob/master/proposed/phpdoc.md) and the spec for ["Inline PHPDoc"](https://github.com/phpDocumentor/fig-standards/blob/master/proposed/phpdoc.md#54-inline-phpdoc), but thought the second example in [8.13](https://github.com/phpDocumentor/fig-standards/blob/master/proposed/phpdoc.md#813-param) was very odd.  The example shows a `@param array` being described with an inline PHPDoc, with possible array elements defined with `@type` followed by a type, and what looked like variable names where key names should be. Is there a reason `$required` and `$label` shouldn't be replaced with `'required'` and `'label'`?

**Comment by ashnazg** [comment]
`@type` has since been reverted to using `@var` instead.

Since the `@var` tag does _not_ include its target variable name in the tag syntax, I think I need to remove that from the `@param` example that shows an _inline PHPDoc_.  That alone will remove the ambiguity you referenced initially.

Regarding your best practice questions:
* I'd carefully choose which order you want to _explain_ the various options, and explicitly say in each Description which array key to use for it, regardless of whether the key is `Option1` or `1`.  The text Description is the only useful way I see to do this.  Trying to come up with a structured syntax doesn't seem reasonable to me.
* Here, I'd follow the same advice as the previous bullet.  It's all about how you lay out your text and how well you explain things in your Descriptions.  I don't see a large enough benefit to engineering something for static analysis for these use cases.

Ping @ondrejmirtes @muglug @neuro159 @mindplay-dk @GaryJones @mvriel @jaapio for opinions.

**Comment by ashnazg** [comment]
If this needs to be pursued further, please bring this up as a new thread on the FIG mailing list for discussion -- https://groups.google.com/forum/#!forum/php-fig
