### ISSUE TITLE
php-doc: Markdown issues

### ISSUE THREAD

**Issue by mindplay-dk** [phpDocumentor/fig-standards#72]
Some minor issues regarding Markdown.

From the current php-doc proposal:

> Any application parsing the Description is RECOMMENDED to support the Markdown mark-up language for this field

and:

> The description of a tag MUST support Markdown as a formatting language

Why is one a MUST and the other only RECOMMENDED?

Doesn't make any sense - if Markdown is a MUST in any place in the spec, parsing Markdown is an absolute dependency, so there's no sense in being strict about it in one clause and lax about it in another.

Either Markdown should be RECOMMENDED everywhere, or should be a MUST everywhere, consistently - personally, I'd prefer it's a MUST so that we can count on it always being supported everywhere.

My other issue is, Markdown is not a standard - not even remotely. It's all over the place. I would suggest recommending a specific standard, such as [CommonMark](http://commonmark.org/) which is probably, at this time, the closest thing to becoming a real spec in the Markdown landscape.

I also would strongly recommend adding at least a short section describing the use of Markdown in the context of php-doc in general - one thing that's missing, is a description of what's allowed or expected in the `[]()` link tags. If the spec doesn't prescribe anything, you can count on documentation generators immediately starting to add support for things like `[ClassName](...)` and `[Filename](...)` and `[ClassName::CONST_NAME](...)` and so forth - which would make a lot of sense, but it would be nice to have this at least briefly described in the php-doc spec to ensure everybody doesn't come up with inconsistent syntax and features in this regard.

**Comment by mindplay-dk** [comment]
PS: Php Storm 8 apparently [already added Markdown support](http://blog.jetbrains.com/phpstorm/2014/04/phpstorm-8-markdown-support-in-phpdoc-blocks/) based on [John Gruber's](https://daringfireball.net/projects/markdown/syntax) Markdown description - so vendors are already making up their own minds about which Markdown description to follow, and this one has no real spec, just a loose description.

**Comment by mvriel** [comment]
You are right; it should be consistent. The first was changed from MUST to RECOMMENDED after feedback from the community, partly due to the 'there is no real standard' issue.

Although I would like CommonMark to be a de-facto standard in this the original author of Markdown has indicated that he does not accept CommonMark and as such I consider it to be unreliable when thinking of the future.

As such I agree with the community that it would make sense to make it recommended but not required. It will also remove a dependency from this spec which you could argue whether it should be there.

**Comment by mindplay-dk** [comment]
> the original author of Markdown has indicated that he does not accept CommonMark

That's really sort of beside the point - it's the closest thing we have to a standard. It's already widely accepted - there are plenty of implementations already. And there is no alternative.

The "loose notes" original Markdown description is of no real use, because no one (including the people who worked hard on CommonMark) can be sure if they're interpreting it correctly or not. It may not be perfect, but it's already widely accepted, and it's the best we've got. Certainly better than saying "some Markdown, take your pick", or saying nothing at all? To say that you follow the original description basically leaves everyone in the dark, where they were already, as there's already hundreds of interpretations (literally) of that description going around.

**Comment by colinodell** [comment]
I'd also like to give a strong +1 for CommonMark.

> the original author of Markdown has indicated that he does not accept CommonMark

John Gruber (the inventor of Markdown) doesn't accept CommonMark because, in his opinion, [Markdown is about writing, not about generating HTML output](http://shindoisshin.net/blog/2014/9/6/standard-markdown-controversy); if people really wish to output HTML, [they should have freedom to decide how to do this](https://twitter.com/gruber/status/507670720886091776). Therefore, any attempts to standardize parsing and/or output "[miss the point](https://twitter.com/gruber/status/509060983990812673)".

Unfortunately this philosophy doesn't work well for programmers who expect consistent output from their tools.

I think the logical question to ask is whether the Markdown used in docblocks will likely be converted into HTML.  If so, then I feel it's extremely important to require (or at least strongly recommend) a well-specified "flavor" like CommonMark to ensure that markup is always interpreted the same way.  Otherwise you'd end up with different tools generating [different HTML for complex/ambiguous syntax](http://johnmacfarlane.net/babelmark2/faq.html#what-are-some-examples-of-interesting-divergences-between-implementations) which would be a headache for maintainers to fix.

I also disagree with your assessment of CommonMark being "unreliable" - its the most stable, well-specified "flavor" out there and continues to grow in popularity.

Because the goal of this project is to standardize things, I think it makes sense to incorporate relevant standards where applicable to ensure standardized behavior and expectations for everyone.  I'd therefore urge you to reconsider your position.

**Comment by sheldon9527** [comment]
> [`****`](

- [ ] # 1. url
fkjdskjvdskj
)

**Comment by ashnazg** [comment]
Discussion of this is active on #123, so closing this one.
